name: terraform
run-name: "[terraform-${{ github.event_name == 'pull_request' && 'verify' || 'deploy' }}] ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message }}"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'infra/*'
  push:
    branches:
      - main
    paths:
      - 'infra/*'
    tags-ignore:
      - '*'

defaults:
  run:
    working-directory: ./infra

permissions:
  contents: read  # This is required for actions/checkout
  id-token: write # This is required for requesting the JWT

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.7.5'
      - name: Setup tflint
        if: github.event_name == 'pull_request'
        uses: terraform-linters/setup-tflint@v1
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform init
      - name: tflint
        if: github.event_name == 'pull_request'
        run: |
          tflint
      - name: Terraform validate & format
        if: github.event_name == 'pull_request'
        run: |
          terraform validate
          terraform fmt -check -recursive -diff
      - name: Trivy scan
        if: github.event_name == 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: ./infra
          hide-progress: false
          format: github
          exit-code: '1'

      - name: Terraform plan
        env:
          TF_VAR_repo: ${{ github.repositoryUrl }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform plan ${{ github.event_name == 'pull_request' && '' || '-out=planfile' }}
      - name: Terraform apply
        if: github.event_name == 'push'
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: terraform apply "planfile"
